In [ ]:
import matplotlib
import numpy
import scipy
from matplotlib import pyplot
from mpl_toolkits.mplot3d import Axes3D
from numpy import random
from scipy import stats

In [ ]:
# Form a three-dimensional array with 36 elements.
# This is also known as a rectangular prism.
# Higher-dimensional arrays are more difficult to visualize, but still follow the numpy "arrays within an array" pattern.
three_d_array = numpy.arange(36).reshape(3, 4, 3)
three_d_array, three_d_array.shape

In [ ]:
# Vectorization - Express operations as ocurring on entire arrays rather than their individual elements.

# Consider this 1-dimensional vector of True and False, from which we want to count the nuymber of "False to True" transitions in the sequence.
numpy.random.seed(444)
x = numpy.random.choice([False, True], size=100000)

count = 0
for i, j in zip(x[:-1], x[1:]):
    if j and not i:
        count += 1
print(count)

In [ ]:
# In vectorized form, there's no explicit for-loop or direct reference to the individual elements.
numpy.count_nonzero(x[:-1] < x[1:])

In [ ]:
def generate_fib(num_fibs):
    fib_members = []
    current = 0
    next_value = 1
    for i in range(0, num_fibs):
        temp = current + next_value
        fib_members.append(temp)
        current = next_value
        next_value = temp
    return fib_members
generate_fib(12)

In [ ]:
a0 = numpy.array([4, 2, 0, 1, 10, 4, 7, 22, 9, 90, 12])
a1 = numpy.array(generate_fib(11))

In [ ]:
stacked_vertically = numpy.vstack((a0, a1))
# Each numpy array can be thought of as a row in the resulting array.
stacked_vertically

In [ ]:
stacked_horizontally = numpy.hstack((a0, a1))
# This is effectively an append.
stacked_horizontally

In [ ]:
stacked_depth = numpy.dstack((a0, a1))
# Each numpy array can be thought of as a column in the resulting array.
stacked_depth

In [ ]:
first_random_gen = random.default_rng()
values_generated = first_random_gen.standard_normal(10)
more_values = first_random_gen.standard_normal(10)
stacked_random_values = numpy.vstack((values_generated, more_values))
stacked_random_values

In [ ]:
numpy.ravel(stacked_random_values)

In [ ]:
list_to_arrayify = []
for i in range(0, 10):
    list_to_arrayify.append(i)
    
exercises_array = numpy.array(list_to_arrayify)
exercises_array

# This is all well and good, BUT, the numpy canonical way appears to be:
array = numpy.arange(10)
array

In [ ]:
# The distinction between these two appears to be the fact that the "full" method takes an additional
# argument (in this case, set to True) called fill_value. Not sure what it does exactly. TODO: Read up.
array_of_bools = numpy.full((3, 3), True, dtype=bool)
array_of_bools

alter_array_of_bools = numpy.ones((3, 3), dtype=bool)
alter_array_of_bools

In [ ]:
# Reusing an array defined above.
odd_members = array % 2 != 0
odd_members

# Technically, this did not satisfy our requirement: We were asked to extract the odd numbers
# not identify where they are in the array.
alternate_method = array[odd_members]
alternate_method

# One liner:
odd_numbers = array[array % 2 != 0]
odd_numbers

In [ ]:
# it looks like we pass in the predicate, the replacement value, and the array:
# If we needed to change this array in place, rather than creating a new object, we could:
# numpy.where(array % 2 == 1, -1, array)
new_array = numpy.where(array % 2 == 1, -1, array)
new_array

In [ ]:
reshaped_array = numpy.reshape(array, (2, 5))
reshaped_array

In [ ]:
# array generation and stacking
# Generate an array within a given range and reshape it to have 2 rows and 5 columns
a = numpy.arange(10).reshape(2, -1)
a

# Generate an array with repetitive values. The arguments here are: value to populate (1) and number of constituents to implement (10).
b = numpy.repeat(1, 10).reshape(2, -1)
b

# The exercise here is to stack the arrays (a and b) vertically. vstack is the first function that comes to mind:
stack_a_b = numpy.vstack((a, b))
print(stack_a_b)

# There are alternatives, however:
# Should play with this "axis" variable and see how it operates on the array.
# 
# In general, for arrays with > 2 dimensions, hstack will stack arrays along their second axes, vstack will stack along their first
# and concatenate allows for optional arguments giving the number of the axes along which the concatenation should happen.
# 
# This axis variable pivots the axis of the array.
# Axis=0:
# [[0 1 2 3 4]
#  [5 6 7 8 9]
#  [1 1 1 1 1]
#  [1 1 1 1 1]]
# 
# Axis=1:
# [[0 1 2 3 4 1 1 1 1 1]
#  [5 6 7 8 9 1 1 1 1 1]]
concatenated = numpy.concatenate([a, b], axis=0)
print(concatenated)

# This one is interesting.
# This translates slice objects to concatenation along the first axis.
# There are two general use cases for this method:
# If the index expression contains comma separated arrays, then stack them along their first axis.
# If the index expression contains slice notation or scalars then create a 1-D array with a range indicated bu the slice notation.
# 
r = numpy.r_[a, b]
r

In [ ]:
# Stack the arrays a and b horizontally:
horizontal_test = numpy.hstack((a, b))
print(horizontal_test)

# Alternative method is to use the concatenate function, and change the axis on which we concat:
alt_horizontal_test = numpy.concatenate([a, b], axis=1)
print(alt_horizontal_test)

# Or another alternate:
# This translates slice objects to concatenation along the second axis.
# This function is short-hand for numpy.r_['-1, 2, 0', index_expression], which makes this function useful, given the operations's common occurrence.
# In particular, arrays will be stacked along their last axis after being upgraded to at least 2-D with 1's post-pended to the shape 
# (column vectors made out of 1-D arrays.)
# 
c_horizontal = numpy.c_[a, b]
c_horizontal

In [ ]:
def get_diff_of_array_len(array_zero, array_one):
    if len(array_zero) > len(array_one):
        return len(array_zero) - len(array_one)
    elif len(array_one) > len(array_zero):
        return len(array_one) - len(array_zero)
    else:
        # Lengths are the same, so there is no diff.         
        return 0


inequality_test_zero = numpy.arange(10)
inequality_test_one = numpy.arange(15)
h_stack = numpy.hstack((inequality_test_zero, inequality_test_one))
# This works, because we are effectively appending one array onto another.
print(h_stack)

# This does NOT work, because the array dimensions for the concatenation axis do not match.
# v_stack = numpy.vstack((inequality_test_zero, inequality_test_one))

# Need to know how far the shorter array needs to be extended.
diff = get_diff_of_array_len(inequality_test_zero, inequality_test_one)
print(diff)

# What if we really need to stack these arrays as rows in a data frame, despite the size diff?
# We can "null" extend the shorter of the two arrays so that they can be stacked:
inequality_test_zero = numpy.pad(inequality_test_zero, (0, diff), 'constant')

# Now we can stack the arrays:
v_stack = numpy.vstack((inequality_test_zero, inequality_test_one))
v_stack

In [ ]:
import numpy
grades = numpy.array([[93, 95],
                      [84, 100],
                      [99, 87]])

# slicing
# This grabs the 1th index of each array in the parent array.
print(f'0:3, 1 = {grades[0:3, 1]}')

# This is equivalent to grades[1:3, 1], supposedly, although there is no third index in either of these shapes.
# Perhaps this is a standard counting scheme. Test below.
# This grabs the 1th index of each array including and after the 1th array in the parent array. 
print(f'1:, 1 = {grades[1:, 1]}')

# Yup, this returns the same thing as the one above.
print(f'1:3, 1 = {grades[1:3, 1]}')

# Equivalent to grades[0:3, 0:1]
# This gets all of the values at the 0th index of each array.
print(f'0:3, 0:1 = {grades[:, :1]}')